DB_PATH = "src/infra/db/bots.db"
# DB_PATH = "bots.db"
DB_CONNECTION = f"sqlite:///{DB_PATH}"
ASYNC_DB_CONNECTION = DB_PATH

DEFAULT_HTTP_TIMEOUT = 5
GET_UPDATES_TIMEOUT = 30

# RABBIT_CONNECTION = "amqp://admin:Linux623622@80.78.251.33/"
RABBIT_CONNECTION = "amqp://admin:Linux623622@localhost/"
RABBIT_MESSAGE_TTL = 1000 * 60 * 30  # 30 min
RABBIT_COMMON_QUEUE = "common_in_msg"

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_QUIZ_DB = 1
REDIS_SCENARIO_DB = 2
