version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    #volumes:
    #  - 'redis_data:/bitnami/redis/data'

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    ports:
#      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_SECURE_PASSWORD: "no"
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
    volumes:
        - ./init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local