"""add columns

Revision ID: 92b44bf95062
Revises: a5b70f54ba1a
Create Date: 2022-10-25 00:49:11.279461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b44bf95062'
down_revision = 'a5b70f54ba1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('personal_data_agree', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'personal_data_agree')
    op.drop_column('user', 'occupation')
    # ### end Alembic commands ###
