"""scenario

Revision ID: a5b70f54ba1a
Revises: 0cabd0f230e8
Create Date: 2022-10-22 18:37:24.248231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b70f54ba1a'
down_revision = '0cabd0f230e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rel_bot', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('next_step', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_answer_validation', sa.String(length=50), nullable=True),
    sa.Column('buttons', sa.Text(), nullable=True),
    sa.Column('db_target', sa.String(length=70), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rel_bot'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario__id__rel_bot', 'scenario', ['rel_bot', 'step'], unique=False)
    op.create_index('ix_scenario__rel_bot', 'scenario', ['rel_bot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scenario__rel_bot', table_name='scenario')
    op.drop_index('ix_scenario__id__rel_bot', table_name='scenario')
    op.drop_table('scenario')
    # ### end Alembic commands ###
